<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smc_test_bot">


    <!-- ################### inertia macros  ############################-->
    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>
    <!-- ###################################################################################### -->


    <!-- ################### color materials  ############################-->
    <material name="orange">
        <color rgba="1 0.55 0 1"/>
    </material>

    <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
    </material>

    <material name="silver">
        <color rgba="0.6 0.6 0.6 1"/>
    </material>
    <!-- ###################################################################################### -->


    <!-- ################### robot properties  ############################-->
    <xacro:property name="chassis_length" value="0.25"/>
    <xacro:property name="chassis_width" value="0.19"/>
    <xacro:property name="chassis_height" value="0.10"/>
    <xacro:property name="chassis_mass" value="3.0"/>

    <xacro:property name="wheel_seperation" value="0.22"/>
    <xacro:property name="wheel_radius" value="0.034"/>
    <xacro:property name="wheel_width" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.08"/>

    <!-- <xacro:property name="castor_wheel_radius" value="0.025"/> -->
    <xacro:property name="castor_wheel_mass" value="0.04"/>
    <!-- ###################################################################################### -->
    







    <!-- BASE LINK -->

    <!-- <base joint/> -->
    <link name="base_link">  
    </link>

    <!-- ################# -->





    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <link name="chassis">
        <visual>
          <origin xyz="${-chassis_length/6} 0 ${chassis_height/2}" rpy="0 0 0"/>
          <geometry>
              <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
          </geometry>
          <material name="orange"/>
        </visual>
        <collision>
           <origin xyz="${-chassis_length/6} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${-chassis_length/6} 0 ${wheel_radius*2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <!-- <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo> -->

    <!--  ########################### -->




    <!-- LEFT DRIVE WHEEL -->

    <joint name="left_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="left_wheel"/>
      <origin xyz="0 ${wheel_seperation/2} 0" rpy="${-pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="black"/>
      </visual>
      <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>

    <!-- <gazebo reference="left_wheel">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000</kp>
      <kd>0.001</kd>
      <minDepth>0.001</minDepth>
      <fdir1>${fdir}</fdir1>
      <material>Gazebo/FlatBlack</material>
    </gazebo> -->

    <!-- ############################# -->





    <!-- RIGHT DRIVE WHEEL -->

    <joint name="right_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="right_wheel"/>
      <origin xyz="0 ${-wheel_seperation/2} 0" rpy="${-pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="right_wheel">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="black"/>
      </visual>
      <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>

    <!-- <gazebo reference="right_wheel">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000</kp>
      <kd>0.001</kd>
      <minDepth>0.001</minDepth>
      <fdir1>${fdir}</fdir1>
      <material>Gazebo/FlatBlack</material>
    </gazebo> -->

    <!-- ############################# -->






    <!--  CASTOR WHEEL LINK -->

    <joint name="castor_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="castor_wheel"/>
        <origin xyz="${-chassis_length/2} 0 0"/>
    </joint>


    <link name="castor_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${castor_wheel_mass}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- <gazebo reference="castor_wheel">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <fdir1>1 0 0</fdir1>
        <minDepth>0.01</minDepth>
        <material>Gazebo/Silver</material>
    </gazebo> -->

    <!--  ########################### -->







    <!-- ############# add ros2_control => INSERT SMC_ROS_HW_PLUGIN ############### -->

    <ros2_control name="smc_differential_drive_control" type="system">

      <hardware>
        <plugin>smc_ros_hw_plugin/SMCDriverHardware</plugin>
        <param name="motorA_wheel_name">left_wheel_joint</param>
        <param name="motorB_wheel_name">right_wheel_joint</param>
        <param name="port">/dev/ttyUSB0</param>
      </hardware>

      <joint name="left_wheel_joint">
        <command_interface name="velocity">
            <param name="min">-8.0</param>
            <param name="max">8.0</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="right_wheel_joint">
        <command_interface name="velocity">
            <param name="min">-8.0</param>
            <param name="max">8.0</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

    </ros2_control>

    <!-- ################################################################# -->

</robot>